apiVersion: apps/v1
kind: Deployment
metadata:
  name: hgneon-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hgneon-proxy
  template:
    metadata:
      labels:
        app: hgneon-proxy
    spec:
      containers:
      - name: hgneon-proxy
        image: hgneon/proxy:v4.4.3
        ports:
        - containerPort: 9999
        - containerPort: 9899
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "400m"
        env:
        - name: POSTGRES_USERNAME
          valueFrom:
            secretKeyRef:
              name: handler-mypostgres-postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: handler-mypostgres-postgres-secret
              key: password
        - name: PGPOOL_PASSWORD_ENCRYPTION_METHOD
          value: "scram-sha-256"
        - name: PGPOOL_ENABLE_POOL_PASSWD
          value: "true"
        - name: PGPOOL_SKIP_PASSWORD_ENCRYPTION
          value: "false"
        # The following settings are not required when not using the Pgpool-II PCP command.
        # To enable the following settings, you must define a secret that stores the PCP user's
        # username and password.
        - name: PGPOOL_PCP_USER
          valueFrom:
            secretKeyRef:
              name: handler-pgpool-pcp-secret
              key: username
        - name: PGPOOL_PCP_PASSWORD
          valueFrom:
            secretKeyRef:
              name: handler-pgpool-pcp-secret
              key: password
        - name: PCPPASSFILE
          value: "/var/lib/pgsql/.pcppass"
        - name: KUBECONFIG
          value: "/k8sconfig/my-cluster.yml"
        volumeMounts:
        - name: hgneon-proxy-config
          mountPath: /config
        - name: hgneon-proxy-scripts
          mountPath: /proxy-scripts
        - name: hgneon-proxy-k8s-specs
          mountPath: /k8sconfig
        - name: hgneon-proxy-endpoint-manifest
          mountPath: /endpoint
        #- name: pgpool-tls
        #  mountPath: /config/tls
      volumes:
      - name: hgneon-proxy-config
        configMap:
          name: hgneon-proxy-config
      - name: hgneon-proxy-scripts
        configMap:
          name: handler-pgpool-scripts
          defaultMode: 0755
      - name: hgneon-proxy-k8s-specs
        configMap: 
          name: handler-pgpool-k8s-specs
      - name: hgneon-proxy-endpoint-manifest
        configMap:
          name: hgneon-proxy-endpoint-manifest
      # Configure your own TLS certificate.
      # If not set, Pgpool-II will automatically generate the TLS certificate if ssl = on.
      #- name: pgpool-tls
      #  secret:
      #    secretName: pgpool-tls
---
apiVersion: v1
kind: Service
metadata:
  name: hgneon-proxy-service
  labels:
    app: hgneon-proxy-service
spec:
  type: ClusterIP
  selector:
    app: hgneon-proxy
  ports:
  - name: hgneon-proxy-port
    port: 9999
    targetPort: 9999
