apiVersion: v1
kind: ConfigMap
metadata:
  name: hgneon-proxy-config
  labels:
    name: hgneon-proxy-config
data:
  pgpool.conf: |-
    listen_addresses = '*'
    port = 9999
    pcp_listen_addresses = '*'
    pcp_port = 9899
    pcp_socket_dir = '/var/run/pgpool'
    sr_check_period = 0
    sr_check_user = 'cloud_admin'
    health_check_period = 0
    health_check_user = 'cloud_admin'
    backend_clustering_mode = 'streaming_replication'
    num_init_children = 32
    max_pool = 8
    child_life_time = 300
    child_max_connections = 0
    connection_life_time = 0
    client_idle_limit = 0
    connection_cache = on
    load_balance_mode = off
    ssl = off
    enable_pool_hba = off
    failover_on_backend_error = off
    log_min_messages = warning
    # hg added
    statement_level_load_balance = off
    log_statement = on
    log_per_node_statement = on
    search_primary_node_timeout = 300
    recovery_user = 'cloud_admin'
    hostname0 = ''
    failover_when_quorum_exists = off
    replication_mode = off

  # If pool_hba.conf isn't configured, Pgpool-II will automatically generate it.
  # Note that to use pool_hba.conf you must set enable_pool_hba = on.
  #pool_hba.conf: |-
  #  local      all         all                          trust
  #  hostssl    all         all         0.0.0.0/0        scram-sha-256
