apiVersion: apps/v1
kind: Deployment
metadata:
  name: stats-server
spec:
  selector:
    matchLabels:
      app: stats
  replicas: 1
  template:
    metadata:
      labels:
        app: stats
    spec:
      containers:
      - name: stats
        image: hgneon/stats:v1.0.0
        imagePullPolicy: Always
        ports:
        - containerPort: 9009
        
---
apiVersion: v1
kind: Service
metadata:
  name: stats-service
spec:
  type: ClusterIP
  selector:
    app: stats
  ports:
  - name: stats-service
    port: 9009
    targetPort: 9009
