
apiVersion: apps/v1
kind: Deployment
metadata:
  name: haproxy-rest-deployment
spec:
  selector:
    matchLabels:
      app: haproxy
  replicas: 1
  template:
    metadata:
      labels:
        app: haproxy
    spec:
      containers:
      - name: haproxy
        image: haproxy:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: haproxy-rest
            mountPath: /usr/local/etc/haproxy/
      volumes:
        - name: haproxy-rest
          configMap:
            name: haproxy-rest
            defaultMode: 0755
        
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-rest-service
spec:
  type: NodePort
  selector:
    app: haproxy
  ports:
  - name: haproxy
    port: 8080
    targetPort: 8080
    nodePort: 30088
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-psql-service
spec:
  type: NodePort
  selector:
    app: haproxy
  ports:
  - name: haproxy
    port: 8081
    targetPort: 8081
    nodePort: 30089
---
apiVersion: v1
kind: Service
metadata:
  name: haproxy-map-service
spec:
  type: ClusterIP
  selector:
    app: haproxy
  ports:
  - name: haproxy-map
    port: 9999
    targetPort: 9999
